language: android
jdk: oraclejdk8
sudo: required 
env:
    global:
        - ANDROID TOOLS_API=24
        - ANDROID_BUILD_TOOLS=24.0.2
        
android:
components:
# Uncomment the lines below if you want to
# use the latest revision of Android SDK Tools
- platform-tools
- tools

# The BuildTools version used by your project


# The SDK version used to compile your project



# Specify at least one system image,
# if you need to run emulator(s) during your tests
#- sys-img-armeabi-v7a-android-22
#- sys-img-armeabi-v7a-android-17

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- "./gradlew dependencies || true"
script:
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"
